name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  terraform:
    name: Terraform fmt & validate
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infrastructure
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform fmt (check)
        run: terraform fmt -check -recursive

      - name: Terraform init (no backend)
        run: terraform init -backend=false

      - name: Terraform validate
        run: terraform validate -no-color

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4

      - name: TFLint init
        run: tflint --init

      - name: TFLint run
        run: tflint -f compact

      - name: tfsec (static analysis)
        uses: aquasecurity/tfsec-action@v1
        with:
          working_directory: infrastructure
        continue-on-error: true

  node_lambda:
    name: Lambda deps & audit
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: lambda
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: lambda/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Security audit (high severity)
        run: npm audit --audit-level=high
        continue-on-error: true

      - name: Test packaging
        run: zip -q -r function.zip index.js simple-rag.js package.json node_modules
